name: warranty

services:
  backend:
    image: warranty-backend:prod
    build:
      context: ./backend
      target: production
    container_name: warranty-fastapi
    restart: always
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=production
      - RECORDS_PER_PAGE=30
    env_file:
      - ./.env
    volumes:
      - ./instance:/app/instance

  frontend:
    image: warranty-frontend:prod
    build:
      context: ./frontend
      target: production
    container_name: warranty-vue
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - backend
