name: warranty

services:
  backend:
    build:
      context: ./backend
      target: production
    container_name: warranty-fastapi
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    volumes:
      - ./instance:/app/instance

  frontend:
    build:
      context: ./frontend
      target: production
    container_name: warranty-vue
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - backend
